# Generated by Django 6.0 on 2025-12-18 03:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('firstapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('M', 'Member'), ('A', 'Admin'), ('D', 'Driver')], db_index=True, default='M', max_length=1),
        ),
        migrations.CreateModel(
            name='DeliveryProof',
            fields=[
                ('order', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='delivery_proof', serialize=False, to='firstapp.order')),
                ('image', models.ImageField(upload_to='delivery_proofs/')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('notes', models.TextField(blank=True, default='')),
                ('driver', models.ForeignKey(limit_choices_to={'role': 'D'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='delivered_orders', to='firstapp.user')),
            ],
            options={
                'verbose_name': 'Delivery Proof',
                'verbose_name_plural': 'Delivery Proofs',
                'db_table': 'delivery_proof',
                'ordering': ['-uploaded_at'],
            },
        ),
    ]
